config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "members#index"
  resources :users, only: [:edit, :update]
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def create
    @member = Member.new(
      name: session[:name],
      tel: session[:tel],
      birthday: session[:birthday],
      postcode: session[:postcode],
      city: session[:city],
      block: session[:block],
      building: session[:building],
      secularname: session[:secularname],
      dharmaname: session[:dharmaname],
      deceased: session[:deceased]
    )
    if @member.save
      session[:id] = @member.id
      redirect_to root_path
    else
      render '/signup/step1'
    end
  end

  def step1
    @member = Member.new
  end

  def step2
    session[:name] = member_params[:name]
    session[:tel] = member_params[:tel]
    session[:birthday] = member_params[:birthday]
    session[:postcode] = member_params[:postcode]
    session[:city] = member_params[:city]
    session[:block] = member_params[:block]
    session[:building] = member_params[:building]
    @member = Member.new 
  end

  def step3
    session[:secularname] = member_params[:secularname]
    session[:dharmaname] = member_params[:dharmaname]
    session[:deceased] = member_params[:deceased]
    @member = Member.new 
  end

  private

  def member_params
    params.require(:member).permit(
      :name,
      :tel,
      :birthday,
      :postcode,
      :city,
      :block,
      :building,
      :secularname,
      :dharmaname,
      :deceased,
      :spring,
      :summer,
      :autumn,
      :winter
  )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Jionkun12
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/members/_main_chat.html.haml
.list-main
  .main-header
    .main-header__list
      %p.main-header__list__name
        会員データor一覧
    .main-header__edit
      = link_to "#", class: "btn" do
        Edit

  .lists
    .list
      .list__upbox
      .list__downbox

  .form
    %form.serch
      .seach_box
        %input{type: "seach", class: "seach_box__text",placeholder: "キーワードを入力"}
      %input{type: "submit", class: "submit-btn", value: "検索"}

app/views/members/_side_bar.html.haml
.item-side
  .side-header
    .side-header__box
      %h3.side-header__box__new
        新規会員登録
      %ul.side-header__box__menu
        %li.side-header__box__menu__new-member
          = link_to step1_signup_index_path do
            = icon('far', 'edit')
        %li.side-header__box__menu__edit
          = link_to edit_user_path(current_user) do
            = icon('fas', 'cog')
            
  .items
    = link_to "#", class: "item__member" do
      %p.item__member__list
        会員データ
    = link_to "#", class: "item__list" do
      %p.item__list__register
        申込み一覧

app/views/members/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/signup/step1.html.haml
.member-form
  %h1 新規会員登録
  .new_member
    = form_for @member, url: step2_signup_index_path, method: :get do |f|
      .new_member__field
        .new_member__field--left
          = f.label :name, "名前", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :name, class: "member-form__name member-form__input", placeholder: "名前を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :tel, "電話番号", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :tel, class: "member-form__tel member-form__input", placeholder: "電話番号を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :birthday, "誕生日", class: 'member-form__label'
        .new_member__field--right
          = f.date_select :birthday, class: "member-form__birthday member-form__input", use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1)

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :postcode, "郵便番号", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :postcode, class: "member-form__postcode member-form__input", placeholder: "郵便番号を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :city, "都道府県", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :city, class: "member-form__city member-form__input", placeholder:"都道府県を入力してください"
      
      .new_member__field.clearfix
        .new_member__field--left
          = f.label :block, "市町村", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :block, class: "member-form__block member-form__input", placeholder:"市町村を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :building, "番地", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :building, class: "member-form__building member-form__input", placeholder:"番地を入力してください"
      
      .new_member__field.clearfix
        .new_member__field--left
        .new_member__field--right
          = f.submit "次の項目へ", class: "member-form__action-btn"

app/views/signup/step2.html.haml
.member-form
  %h1 新規会員・故人データ登録
  .new_member
    = form_for @member, url: step3_signup_index_path, method: :get do |f|
      .new_member__field
        .new_member__field--left
          = f.label :secularname, "俗名", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :secularname, class: "member-form__secularname member-form__input", placeholder: "俗名を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :dharmaname, "戒名", class: 'member-form__label'
        .new_member__field--right
          = f.text_field :dharmaname, class: "member-form__dharmaname member-form__input", placeholder: "戒名を入力してください"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :deceased, "命日", class: 'member-form__label'
        .new_member__field--right
          = f.date_select :deceased, class: "member-form__deceased member-form__input", use_month_numbers: true,start_year: 1930, end_year: (Time.now.year), default: Date.new(1989, 1, 1)
      
      .new_member__field.clearfix
        .new_member__field--left
        .new_member__field--right
          = f.submit "次の項目へ", class: "member-form__action-btn"

app/views/signup/step3.html.haml
.member-form
  %h1 お申し込み登録
  .new_member
    = form_for @member, url: signup_index_path, method: :post do |f|
      .new_member__field
        .new_member__field--left
          = f.label :spring, "春期彼岸お申し込み", class: 'member-form__label'
        .new_member__field--right
          = f.check_box :spring, class: "member-form__spring member-form__input"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :summer, "お施餓鬼お申し込み", class: 'member-form__label'
        .new_member__field--right
          = f.check_box :summer, class: "member-form__summer member-form__input"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :autumn, "秋期彼岸お申し込み", class: 'member-form__label'
        .new_member__field--right
          = f.check_box :autumn, class: "member-form__autumn member-form__input"

      .new_member__field.clearfix
        .new_member__field--left
          = f.label :winter, "大般若お申し込み", class: 'member-form__label'
        .new_member__field--right
          = f.check_box :winter, class: "member-form__winter member-form__input"

      .new_member__field.clearfix
        .new_member__field--left
        .new_member__field--right
          = f.submit "登録", class: "member-form__action-btn"

      

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 管理ユーザーアカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'